apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
  namespace: ecommerce
type: Opaque
data:
  mongodb-uri: bW9uZ29kYjovL3Jvb3Q6YWRtaW4xMjNAbW9uZ29kYjoyNzAxNy9lY29tbWVyY2VfYXV0aD9hdXRoU291cmNlPWFkbWlu
  jwt-secret: YjU5MWY5ODgxNWEyMmIxMw==
