apiVersion: v1
kind: PersistentVolume
metadata:
  name: ecommerce-pv-0
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data0
  storageClassName: ""
