apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
      - name: product
        image: roshan03ish/product:v1.6
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"
        ports:
        - containerPort: 3001
          name: http
        env:
        - name: MONGODB_PRODUCT_URI
          valueFrom:
            secretKeyRef:
              name: product-secret
              key: mongodb-uri
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: product-secret
              key: jwt-secret
        - name: RABBITMQ_URI
          valueFrom:
            secretKeyRef:
              name: product-secret
              key: rabbitmq-uri
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: product
  namespace: ecommerce
spec:
  selector:
    app: product
  ports:
  - port: 3001
    targetPort: 3001
  type: ClusterIP
